---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  type: NodePort
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      protocol: TCP
      targetPort: 7878  
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222 
    - 192.168.0.223
