---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-radarr
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology
  resources:
    requests:
      storage: 5Gi
