---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        imagePullPolicy: "IfNotPresent"
        image: lscr.io/linuxserver/radarr:latest
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        env:
        - name: TZ
          value: "America/Denver"
        - name: PUID
          value: "555"
        - name: PGID
          value: "321"
        - name: UMASK_SET
          value: "022"
        volumeMounts:
        - name: synology-radarr
          mountPath: /config
          subPath: radarr/config
        - name: data
          mountPath: /data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "iSCSI"
                operator: In
                values:
                - "true"
      volumes:
      - name: synology-radarr
        persistentVolumeClaim:
          claimName: synology-radarr 
      - name: data
        persistentVolumeClaim:
          claimName: synology-data
